# Generated by Django 3.1 on 2020-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_List', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoentry',
            options={'verbose_name_plural': 'Todo Entries'},
        ),
        migrations.AddField(
            model_name='todoentry',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
